steps:
- name: 'aldenhaase/angular-go:base'
  entrypoint: 'bash'
  args: ['-c',' /workspace/bin/build.sh']
  secretEnv: ['POSTMAN_API','SERVER_SIG']
availableSecrets:
  secretManager:
  - versionName: projects/lystr-354722/secrets/POSTMAN_API/versions/1
    env: 'POSTMAN_API'
  - versionName: projects/lystr-354722/secrets/SERVER_SIG/versions/1
    env: 'SERVER_SIG'
timeout: '1600s'