steps:
- name: 'aldenhaase/angular-go:base'
  entrypoint: 'bash'
  args: ['-c',' /workspace/cloudbuild/exports.sh && source /root/.bashrc && /workspace/bin/build.sh']
  secretEnv: ['POSTMAN_API']
availableSecrets:
  secretManager:
  - versionName: projects/lystr-354722/secrets/POSTMAN_API/versions/1
    env: 'POSTMAN_API'