steps:
- name: 'aldenhaase/angular-go:base'
  entrypoint: 'bash'
  args: ['-c',' /workspace/bin/build.sh && gcloud app deploy go-app/app.yaml']
  secretEnv: ['POSTMAN_API']
availableSecrets:
  secretManager:
  - versionName: projects/lystr-354722/secrets/POSTMAN_API/versions/1
    env: 'POSTMAN_API'