steps:
- name: 'aldenhaase/angular-go:base'
  entrypoint: 'bash'
  args: ['-c',' /workspace/cloudbuild/exports.sh && source /root/.bashrc && /workspace/bin/build.sh && gcloud app deploy go-app/app.yaml']