steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c','docker build -t aldenhaase/jic/temp_build:latest -f dockerbuild/Dockerfile ./ && docker run aldenhaase/jic/temp_build:latest gcloud app deploy /workspace/go-app/app.yaml']