steps:
-name: 'node'
  entrypoint: 'npm'
  args: ['install npm install -g @angular/cli']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c','mkdir server/go_app && cp app_config/app.yaml server/go_app && find server/ -name "*.go" -exec cp {} server/go_app/ \; && cd client && ng build --output-path=../server/go_app/ && cd .. &&']
#gcloud app deploy ./server/go_app/app.yaml